name: Keptn Send Event
on: [push]

jobs:
  send_keptn_event:
    runs-on: ubuntu-latest
    name: Sends Keptn Events
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Send Keptn Event
      id: send-keptn-event
      uses: keptn/gh-action-send-event@main
      with:
        keptnApiUrl: "http://20.22.144.90.nip.io/api"
        keptnApiToken: 9mP2nHY39hMSHIBDmg1U9ZcUJ0u6vaefQ3JJrOZ2ipnsf
        event: |
          {
            "data": {
              "configurationChange": {
                "values": {
                  "image": "docker.io/mongo:4.2.2"
                }
              },
              "deployment": {
                "deploymentstrategy": "direct"
              },
              "message": "",
              "project": "sockshop2",
              "result": "",
              "service": "carts-db",
              "stage": "dev",
              "status": ""
            },
            "source": "gh",
            "specversion": "1.0",
            "type": "sh.keptn.event.dev.delivery.triggered",
            "shkeptnspecversion": "0.2.1"
          }
    - name: Print the Keptn Context
      run: echo "The keptn context is ${{ steps.send-keptn-event.outputs.keptnContext }}"
